name: SeatJunky Event Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Run SeatJunky Scraper
        run: |
          python3 sj_events/main.py