name: SeatJunky Event Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Run SeatJunky Scraper
        run: |
          cd sj_events
          poetry run python3 main.py