name: SeatJunky Event Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install poetry Dependencies
        run: poetry install --with dev
      - name: Run SeatJunky Scraper
        run: poetry run python3 sj_events/main.py